const USERNAME="Husnain192";const CACHE_KEY="developer-pulse-v1";const CACHE_MS=15*60*1000;let repositories=[];
const $=id=>document.getElementById(id);
const ageInDays=date=>(Date.now()-new Date(date).getTime())/86400000;
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
function maintenanceScore(repos){const original=repos.filter(repo=>!repo.fork&&!repo.archived);if(!original.length)return 0;const score=original.reduce((sum,repo)=>sum+(ageInDays(repo.pushed_at)<365?1:0)+(repo.description?1:0)+(repo.has_issues?1:0),0);return Math.round(score/(original.length*3)*100)}
function renderMetrics(){const active=repositories.filter(repo=>!repo.archived&&ageInDays(repo.pushed_at)<365).length;const languages=new Set(repositories.map(repo=>repo.language).filter(Boolean));const originals=repositories.filter(repo=>!repo.fork).length;$("activeCount").textContent=active;$("maintenanceScore").textContent=maintenanceScore(repositories)+"%";$("languageCount").textContent=languages.size;$("originalShare").textContent=repositories.length?Math.round(originals/repositories.length*100)+"%":"0%"}
function renderLanguages(){const counts={};repositories.filter(repo=>!repo.fork&&repo.language).forEach(repo=>counts[repo.language]=(counts[repo.language]||0)+1);const rows=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8);const max=Math.max(1,...rows.map(([,count])=>count));$("languageChart").innerHTML=rows.length?rows.map(([language,count])=>`<div class="language-row"><span>${escapeHtml(language)}</span><div class="track"><div class="bar" style="width:${count/max*100}%"></div></div><strong>${count}</strong></div>`).join(""):"<p>No language data available.</p>"}
function renderRepositories(){const query=$("searchInput").value.trim().toLowerCase();const type=$("typeFilter").value;const sort=$("sortSelect").value;let visible=repositories.filter(repo=>{const haystack=[repo.name,repo.description,repo.language].join(" ").toLowerCase();const typeMatch=type==="all"||(type==="original"&&!repo.fork)||(type==="fork"&&repo.fork)||(type==="active"&&!repo.archived&&ageInDays(repo.pushed_at)<365);return haystack.includes(query)&&typeMatch});visible.sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="language"?(a.language||"zzz").localeCompare(b.language||"zzz"):new Date(b.pushed_at)-new Date(a.pushed_at));$("repositoryGrid").innerHTML=visible.map(repo=>{const fresh=ageInDays(repo.pushed_at)<365;const updated=new Intl.DateTimeFormat(undefined,{year:"numeric",month:"short"}).format(new Date(repo.pushed_at));return `<article class="repo"><div class="repo-head"><a href="${repo.html_url}" target="_blank" rel="noreferrer">${escapeHtml(repo.name)} ↗</a><span class="tag ${fresh?"fresh":""}">${fresh?"Active":"Quiet"}</span></div><p>${escapeHtml(repo.description||"No description provided yet.")}</p><div class="tags">${repo.language?`<span class="tag">${escapeHtml(repo.language)}</span>`:""}<span class="tag">${repo.fork?"Fork":"Original"}</span><span class="tag">Updated ${updated}</span></div></article>`}).join("");$("emptyState").hidden=visible.length>0}
async function loadRepositories(force=false){$("statusText").textContent="Loading public repository data…";$("refreshButton").disabled=true;try{const cached=JSON.parse(localStorage.getItem(CACHE_KEY)||"null");if(!force&&cached&&Date.now()-cached.savedAt<CACHE_MS){repositories=cached.data;$("statusText").textContent="Showing recently cached GitHub data";}else{const response=await fetch(`https://api.github.com/users/${USERNAME}/repos?per_page=100&sort=pushed`,{headers:{Accept:"application/vnd.github+json"}});if(!response.ok)throw new Error(`GitHub API returned ${response.status}`);repositories=await response.json();localStorage.setItem(CACHE_KEY,JSON.stringify({savedAt:Date.now(),data:repositories}));$("statusText").textContent=`Live data loaded · ${repositories.length} public repositories`;}renderMetrics();renderLanguages();renderRepositories()}catch(error){$("statusText").textContent=`Could not load GitHub data: ${error.message}`;}finally{$("refreshButton").disabled=false}}
["searchInput","typeFilter","sortSelect"].forEach(id=>$(id).addEventListener(id==="searchInput"?"input":"change",renderRepositories));$("refreshButton").addEventListener("click",()=>loadRepositories(true));loadRepositories();